(tutorial_src) Upload sources to tutorial/tre.
sio2project/task-package-examples pull request #3
Opened 2020-04-23 13:55 UTC by niedziol

Maybe we should keep Makefiles in another folder and create symlinks to them in tutorial_src.

2020-04-26 17:59 UTC, stasio6 approved these changes

2020-04-26 18:32 UTC, stasio6 commented
new_package.sh nie tworzy pliku makefile.in, którego nigdy się nie pamięta
Można rozważyć dodanie templatów podstawowych rzeczy, jak doc, config, a może jakieś programy (zwłaszcza treści, bo resztę idzie od zera zrobić, choć czasem serio łatwiej z templata)

2020-04-28 15:02 UTC, accek requested changes

2020-04-28 15:02 UTC, accek commented on tutorial_src/new_package.sh
> +        ln -rs $_package/$_src $_id/$_src
Omawiane symlinki

2020-04-28 15:02 UTC, accek commented on tutorial_src/package/prog/Makefile
> +	rm -f cykjavalib.java
Tutaj pojawiają się konkretne skróty. Pewnie nie powinny.

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/doc/spiral.cls
> +../../package/doc/spiral.cls
To wygląda jakby było symlinkiem

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/doc/trezad.tex
> +    If $n=0$, print only one line saying "Too small to exist".\\
LaTeX-owe cudzysłowy, czyli po angielsku `` i ''

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/makefile.in
> +OI_TIME = ~/projects/oiejq/oiejq.sh
To takie ciut słabe, żeby tu się jakieś ścieżki pojawiały.
Nie byłoby lepiej, gdyby tutaj zostawić po prostu oiejq.sh i już zrzucić na użytkownika obowiązek zapewnienia, żeby to było w PATH?

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/doc/trezad.tex
> +    Otherwise, print $2*n+3$ lines, $2*n+1$ characters each, representing a drawing
`*` -> \cdot

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/doc/trezad.tex
> +  in their descending order: upper crown, lower crown, and the trunk.
from top to bottom

2020-04-28 15:02 UTC, accek commented on tutorial_src/tre/doc/trezad.tex
> +  in their descending order: upper crown, lower crown, and the trunk.
Także crown to nie jest korona drzewa po angielsku. Może "upper branches" i "lower branches"? Albo "upper/lower part".

2020-04-28 15:31 UTC, accek requested changes

2020-04-28 15:31 UTC, accek commented on tutorial_src/tre/doc/trezad.tex
> +    If $n=0$, print only one line saying ``Too small to exist".\\
Ten prawy cudzysłów to powinny być 2 apostrofy.

2020-04-28 15:44 UTC, accek approved these changes

2020-04-28 15:48 UTC, merged